# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('material', models.CharField(max_length=255, verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b')),
                ('color', models.CharField(max_length=255, verbose_name='\u0426\u0432\u0435\u0442')),
                ('availability', models.BooleanField(default=False, verbose_name='\u041d\u0430\u043b\u0438\u0447\u0438\u0435')),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/odegda')),
                ('date_add', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
