# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20190209_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryDress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/odegda/detail')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Dress')),
            ],
            options={
                'verbose_name': '\u0413\u0410\u041b\u0415\u0420\u0415\u042f \u0414\u041b\u042f \u041f\u041b\u0410\u0422\u042c\u0415\u0412',
                'verbose_name_plural': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0434\u043b\u044f \u0441\u043b\u0430\u0432\u044f\u043d\u0441\u043a\u0438\u0445 \u043f\u043b\u0430\u0442\u044c\u0435\u0432',
            },
        ),
    ]
