# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-09 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_gallerydress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dress',
            options={'verbose_name': '\u0421\u041b\u0410\u0412\u042f\u041d\u0421\u041a\u0418\u0415 \u041f\u041b\u0410\u0422\u042c\u042f', 'verbose_name_plural': '\u041f\u043b\u0430\u0442\u044c\u044f \u0432 \u0441\u043b\u0430\u0432\u044f\u043d\u0441\u043a\u043e\u043c \u0441\u0442\u0438\u043b\u0435'},
        ),
    ]
