# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_auto_20190209_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('material', models.CharField(max_length=255, verbose_name='\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b')),
                ('color', models.CharField(max_length=255, verbose_name='\u0426\u0432\u0435\u0442')),
                ('availability', models.BooleanField(default=True, verbose_name='\u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0435')),
                ('price', models.FloatField(verbose_name='\u0426\u0435\u043d\u0430, \u0433\u0440\u043d.')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('image', models.ImageField(upload_to='img/odegda')),
                ('date_add', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0421\u041b\u0410\u0412\u042f\u041d\u0421\u041a\u0418\u0415 \u041f\u041b\u0410\u0422\u042c\u042f',
                'verbose_name_plural': '\u041f\u043b\u0430\u0442\u044c\u044f \u0432 \u0441\u043b\u0430\u0432\u044f\u043d\u0441\u043a\u043e\u043c \u0441\u0442\u0438\u043b\u0435',
            },
        ),
        migrations.AlterField(
            model_name='gallerydress',
            name='dress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Product'),
        ),
        migrations.DeleteModel(
            name='Dress',
        ),
    ]
